### ISSUE TITLE
Dependancy on wavedrom-cli

### ISSUE THREAD

**Issue by davidcastells** [witchard/ipython-wavedrom#12]
I'm using nbwavefrom in py4hw (although it's not shown in your "dependents" section).
Version 0.2.0 produces the expected output, but newer versions crash because of a dependency on a missing wavedrom-cli package (which is not in pypi, as far as I know).

This issue has raised when trying my py4hw tutorial in binder
https://github.com/davidcastells/py4hw/tree/ca273ded031c4895012ede96a3716c454d1ba53d/tutorial

My goal is to avoid installing anything that is not in pypi...
Can you check wether wavedrom-cli is available, and if not... use the former strategy?

Or, otherwise, do you suggest any other alternative?

BR

**Comment by witchard** [comment]
Hi @davidcastells, thanks for raising this. The wavedrom-cli is actually a nodejs program. I’ve never used binder, so I don’t know if that is possible to install node dependencies?

Previously I used JavaScript in the browser to do the rendering, but it was fiddly and the source of most of the problems people had with this library. Hence removing in favour of wavedrom-cli.

I have seen a fully python re-implementation of wavedrom here: https://github.com/wallento/wavedrompy. However, I chose not to use it because it looked a tad un-maintained. I never tested it out, but if it works ok then I wonder if it makes sense to fallback to that as a rendering approach when wavedrom-cli is not available.

**Comment by witchard** [comment]
Alternatively, you could always pin your nbwavedrom dependency to an older version to continue using the browser based JavaScript rendering

**Comment by davidcastells** [comment]
thanks @witchard ! I will have a look at wavedrompy. By now, I'm restricting to use to nbwavedrom version 0.2.0. 
Best Regards

**Comment by davidcastells** [comment]
thanks @witchard ! I will have a look at wavedrompy. By now, I'm restricting to use to nbwavedrom version 0.2.0.
Best Regards
