### ISSUE TITLE
enable nbcovert

### ISSUE THREAD

**Issue by jcumming** [witchard/ipython-wavedrom#2]
Currently nbconvert does not render the wavedrom output:

````
jupyter-nbconvert --to pdf example.ipynb
[NbConvertApp] Converting notebook example.ipynb to pdf
....datatypefilter.py:41: UserWarning: Your element with mimetype(s) [u'text/html'] is not able to be represented.
  mimetypes=output.keys())
....datatypefilter.py:41: UserWarning: Your element with mimetype(s) [u'application/javascript'] is not able to be represented.
  mimetypes=output.keys())
[NbConvertApp] Writing 19732 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: [u'xelatex', u'notebook.tex']
[NbConvertApp] Running bibtex 1 time: [u'bibtex', u'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 13814 bytes to example.pdf
````
Linking in the wavedrom svg output seems like it might work?

**Comment by witchard** [comment]
Thanks for reporting. Wavedrom rendering is happening client side so I am not 100% sure how to enable this. I will try and take a look when I get a chance. Happy to accept pull requests if you figure anything out too!

**Comment by witchard** [comment]
@jcumming, I have updated the code to use the wavedrom-cli if the phantomjs tool is available. This does the rendering on the server side rather than in the browser and means that we end up storing an SVG file into the ipynb rather than javascript and html. I believe it should now render correctly with nbconvert. Please could you test and let me know if you have any issues (you'll need to install phantomjs).

**Comment by jcumming** [comment]
Awesome, thanks!
